<?php
//cms,2017-10-24 17:35:30,admin
return array(
	'money'=>array(
		1=>array(
			'tlid'=>1,
			'name'=>'游戏币',
			'desc'=>'游戏币可以兑换别的道具，使用特定的功能，玩各种场次',
			'cprc'=>0,
			'typeID'=>1,
			'toolType'=>0
		),
		2=>array(
			'tlid'=>2,
			'name'=>'钻石',
			'desc'=>'钻石',
			'cprc'=>0,
			'typeID'=>1,
			'toolType'=>0
		),
		3=>array(
			'tlid'=>3,
			'name'=>'房卡',
			'desc'=>'房卡',
			'cprc'=>0,
			'typeID'=>1,
			'toolType'=>0
		)
	),
	'tool'=>array(
		11=>array(
			'tlid'=>11,
			'name'=>'黄金圣杯',
			'desc'=>'可以用来砸死可以用来砸死对手的杯子',
			'cprc'=>0,
			'typeID'=>2,
			'toolType'=>1,
			'usable'=>0,
			'show'=>0,
			'keeptime'=>0,
			'persitime'=>0,
			'vip'=>0,
			'm'=>0,
			'mday'=>0,
			'chgsmax'=>0
		),
		12=>array(
			'tlid'=>12,
			'name'=>'啤酒',
			'desc'=>'可以用来砸死对手的杯子',
			'cprc'=>100,
			'typeID'=>2,
			'toolType'=>1,
			'usable'=>0,
			'show'=>0,
			'keeptime'=>0,
			'persitime'=>0,
			'vip'=>0,
			'm'=>0,
			'mday'=>0,
			'chgsmax'=>0
		),
		13=>array(
			'tlid'=>13,
			'name'=>'炸弹',
			'desc'=>'可以吓到对手的炸弹',
			'cprc'=>100,
			'typeID'=>2,
			'toolType'=>1,
			'usable'=>0,
			'show'=>0,
			'keeptime'=>0,
			'persitime'=>0,
			'vip'=>0,
			'm'=>0,
			'mday'=>0,
			'chgsmax'=>0
		),
		14=>array(
			'tlid'=>14,
			'name'=>'玫瑰花',
			'desc'=>'用来表白的神器',
			'cprc'=>100,
			'typeID'=>2,
			'toolType'=>1,
			'usable'=>0,
			'show'=>0,
			'keeptime'=>0,
			'persitime'=>0,
			'vip'=>0,
			'm'=>0,
			'mday'=>0,
			'chgsmax'=>0,
			'reward'=>array(
				0=>array(
					'type'=>'prop',
					'val'=>1,
					'name'=>2,
					'id'=>0
				)
			)
		),
		15=>array(
			'tlid'=>15,
			'name'=>'水桶',
			'desc'=>'可以把对方浇成落汤鸡的水桶',
			'cprc'=>100,
			'typeID'=>2,
			'toolType'=>1,
			'usable'=>0,
			'show'=>0,
			'keeptime'=>0,
			'persitime'=>0,
			'vip'=>0,
			'm'=>0,
			'mday'=>0,
			'chgsmax'=>0,
			'reward'=>array(
				0=>array(
					'type'=>'chip',
					'val'=>'',
					'name'=>'',
					'id'=>0
				)
			)
		),
		16=>array(
			'tlid'=>16,
			'name'=>'肯德鸡',
			'desc'=>'可以喂对方吃的肯德鸡',
			'cprc'=>100,
			'typeID'=>2,
			'toolType'=>1,
			'usable'=>0,
			'show'=>0,
			'keeptime'=>0,
			'persitime'=>0,
			'vip'=>0,
			'm'=>0,
			'mday'=>0,
			'chgsmax'=>0,
			'reward'=>array(
				0=>array(
					'type'=>'chip',
					'val'=>'',
					'name'=>'',
					'id'=>0
				)
			)
		),
		17=>array(
			'tlid'=>17,
			'name'=>'西红柿',
			'desc'=>'用来假装被打流血的水果',
			'cprc'=>100,
			'typeID'=>2,
			'toolType'=>1,
			'usable'=>0,
			'show'=>0,
			'keeptime'=>0,
			'persitime'=>0,
			'vip'=>0,
			'm'=>0,
			'mday'=>0,
			'chgsmax'=>0
		),
		110=>array(
			'tlid'=>110,
			'name'=>'记牌器I-2小时记牌器',
			'desc'=>'记牌器I',
			'cprc'=>10000,
			'typeID'=>2,
			'toolType'=>2,
			'usable'=>1,
			'show'=>1,
			'keeptime'=>0,
			'persitime'=>2,
			'vip'=>0,
			'm'=>0,
			'mday'=>0,
			'chgsmax'=>0
		),
		111=>array(
			'tlid'=>111,
			'name'=>'记牌器II-24小时记牌器',
			'desc'=>'记牌器II-24小时记牌器',
			'cprc'=>40000,
			'typeID'=>2,
			'toolType'=>2,
			'usable'=>1,
			'show'=>1,
			'keeptime'=>0,
			'persitime'=>24,
			'vip'=>0,
			'm'=>0,
			'mday'=>0,
			'chgsmax'=>0
		),
		112=>array(
			'tlid'=>112,
			'name'=>'记牌器III',
			'desc'=>'记牌器III',
			'cprc'=>10000,
			'typeID'=>2,
			'toolType'=>2,
			'usable'=>1,
			'show'=>1,
			'keeptime'=>0,
			'persitime'=>0,
			'vip'=>1,
			'm'=>0,
			'mday'=>0,
			'chgsmax'=>0
		),
		113=>array(
			'tlid'=>113,
			'name'=>'分牌器I',
			'desc'=>'分牌器I',
			'cprc'=>10000,
			'typeID'=>2,
			'toolType'=>2,
			'usable'=>0,
			'show'=>0,
			'keeptime'=>20,
			'persitime'=>20,
			'vip'=>0,
			'm'=>0,
			'mday'=>0,
			'chgsmax'=>0
		),
		114=>array(
			'tlid'=>114,
			'name'=>'分牌器II',
			'desc'=>'分牌器II',
			'cprc'=>20000,
			'typeID'=>2,
			'toolType'=>2,
			'usable'=>1,
			'show'=>1,
			'keeptime'=>0,
			'persitime'=>0,
			'vip'=>1,
			'm'=>0,
			'mday'=>0,
			'chgsmax'=>0
		),
		115=>array(
			'tlid'=>115,
			'name'=>'分牌器III',
			'desc'=>'分牌器III',
			'cprc'=>30000,
			'typeID'=>2,
			'toolType'=>2,
			'usable'=>1,
			'show'=>1,
			'keeptime'=>0,
			'persitime'=>0,
			'vip'=>0,
			'm'=>0,
			'mday'=>0,
			'chgsmax'=>0
		),
		117=>array(
			'tlid'=>117,
			'name'=>'禁比卡',
			'desc'=>'禁比卡，可以禁止比赛',
			'cprc'=>0,
			'typeID'=>2,
			'toolType'=>2,
			'usable'=>1,
			'show'=>1,
			'keeptime'=>0,
			'persitime'=>0,
			'vip'=>0,
			'm'=>0,
			'mday'=>0,
			'chgsmax'=>0,
			'reward'=>array(
				0=>array(
					'type'=>'chip',
					'val'=>'',
					'name'=>'',
					'id'=>0
				)
			)
		)
	),
	'bag'=>array(
		1000=>array(
			'tlid'=>1000,
			'name'=>'新手礼包',
			'desc'=>'新手礼包',
			'cprc'=>0,
			'typeID'=>3,
			'toolType'=>0,
			'usable'=>0,
			'show'=>1,
			'keeptime'=>0,
			'persitime'=>0,
			'vip'=>0,
			'm'=>0,
			'mday'=>0,
			'chgsmax'=>0,
			'reward'=>array(
				0=>array(
					'type'=>'chip',
					'val'=>20000,
					'id'=>1,
					'name'=>'金币'
				),
				1=>array(
					'type'=>'diamond',
					'val'=>10,
					'id'=>2,
					'name'=>'钻石'
				),
				2=>array(
					'type'=>'card',
					'val'=>200,
					'id'=>3,
					'name'=>'房卡'
				),
				3=>array(
					'type'=>'prop',
					'val'=>5,
					'id'=>117,
					'name'=>'禁比卡'
				),
				4=>array(
					'type'=>'prop',
					'val'=>5,
					'id'=>110,
					'name'=>'2小时记牌器'
				)
			)
		)
	),
	'interProp'=>array(
		0=>11,
		1=>12,
		2=>13,
		3=>14,
		4=>15,
		5=>16,
		6=>17
	)
);